import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './resources/css/global/globals.css'
import 'bootstrap-icons/font/bootstrap-icons.css'

const roboto = Roboto({
  weight: ['100','400','500','700','900'],
  subsets: ['latin'],

});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br" > 
      <body className={`${roboto.className} dark-theme`} >{children}</body> 
    </html>
  )
}
